### ISSUE TITLE
Data folder

### ISSUE THREAD

**Issue by KafkaNoNeko** [data301-2020-winter2/course-project-group_1002#10]
Hi, 
I made some changes to the data folder.

1)  When @jiangshaohua1997 added the raw data, a new 'data' folder was created.  I think that is redundant and confusing.  We will not be adding more files to the folder so having '/data/raw/filename' is better than 'data/raw/data/filename'.

2)  Since the processed data is solely @jiangshaohua1997 's work (and we do not know what kind of processing we need right now), I renamed the folder to be reflective of this.

Let me know if any one has any comments!

**Comment by jiangshaohua1997** [comment]
I think these changes are great and will be helpful in the future. I have created a pull request to change my previous path of importing data to the path now.
