### ISSUE TITLE
Submitting pull request 

### ISSUE THREAD

**Issue by KafkaNoNeko** [data301-2020-winter2/course-project-group_1002#12]
Thank you all for creating branches and submitting pull requests for all of your changes!  That is a good practice! :)

However, to make things easier, I propose committing to the main branch directly if you are just making changes to your own analysis files (unless that affects other parts of the project).  What do you think?

**Comment by jiangshaohua1997** [comment]
I am not sure if merging might affect other processes. If not, this might save a good amount of time

**Comment by KafkaNoNeko** [comment]
I think it should be fine if you are just making changes to your ipynb file.   If it does cause issues, git will let us know, and there is also the option of reverting a commit :)

**Comment by jiangshaohua1997** [comment]
This is great, thank you!
