### ISSUE TITLE
Submission

### ISSUE THREAD

**Issue by KafkaNoNeko** [data301-2020-winter2/course-project-group_1002#15]
Good job everyone! We are almost done :))

Who would like to submit the URL on canvas?  I believe it should only be done once.

**Comment by jiangshaohua1997** [comment]
I have submitted the URL below which I believe is the website:
https://github.com/data301-2020-winter2/course-project-group_1002
If you find something incorrect please let me know.

**Comment by KafkaNoNeko** [comment]
Thanks!!
