### ISSUE TITLE
Fail to git clone

### ISSUE THREAD

**Issue by jiangshaohua1997** [data301-2020-winter2/course-project-group_1002#18]
I have failed to use git clone. Could anyone help me with this? Thank you!

![image](https://user-images.githubusercontent.com/76439736/107911785-10fc5980-6f12-11eb-8f45-39fb3720d37f.png)

**Comment by KafkaNoNeko** [comment]
The messages says that cloning has succeeded, but you were not able to checkout of your branch

If DS_Store is not useful, we could maybe create a .gitignore file and add it to the file.

**Comment by KafkaNoNeko** [comment]
What does git status say?

**Comment by jiangshaohua1997** [comment]
For some reason, I pulled it successfully after 10 times of failure, but git status provide me this

![image](https://user-images.githubusercontent.com/76439736/107912439-55d4c000-6f13-11eb-9540-be2ab260c33f.png)

**Comment by KafkaNoNeko** [comment]
Okay, let me try something
