### ISSUE TITLE
Artists

### ISSUE THREAD

**Issue by KafkaNoNeko** [data301-2020-winter2/course-project-group_1002#24]
The values in the artists column is in the format of an array stored as a string.  So I wrote a function to convert the values to lists.

But here's where I am stuck.  Let's say we look at all the artists with popularity above 90.  Some tracks are collaborations, so have more than one artist - that is stored as ['a', 'b'].  Then maybe artist a has another song with popularity above 90 - this is stored as ['a']

What if I want to see the common artists with popularity above 90?  Does anyone have any idea how we could count the number occurrences in the lists?

e.g. 
['a', 'b', 'c']
['a', 'c']
['a']

So count of a would be 3 and count of 'c' would be 2

**Comment by ShaohuaJoseph** [comment]
Thanks a lot for providing us the useful cleaning function!
