### ISSUE TITLE
Dataset and topic description

### ISSUE THREAD

**Issue by KafkaNoNeko** [data301-2020-winter2/course-project-group_1002#6]
I have converted Joseph's description to paragraph form since bullet form should be avoided and have added some ideas of my own.  However, we are still short of the desired number of words. Does anyone have any other ideas?

I have also added some suggestions for the topic and research questions!

I haven't had the opportunity to look at loading the data yet, but I have seen Joseph's (Good job!).  I have noticed that you did quite a bit of cleaning in there but I thought we were only required to load the data this week.  Is that mentioned anywhere in the milestone?  I cannot find it.

Thanks, and Happy Lunar New Year!

**Comment by jiangshaohua1997** [comment]
Hi, thank you for helping us do further analysis. I have a few suggestions on the process.

For the description of the dataset, to increase the number of words, we can explain more about Kaggle and the author, such as some missions and the importance of Kaggle. We can also explain further about the features, like their definitions or functionalities.

For the topic/interest in this dataset, I think your ideas are great! We can search from there and develop more detail.

I also realized that module 1 only requires loading data, but I am interested in the dataset we've chosen and I was trying to get to know it a bit more. 

Thank you, and Happy Lunar New Year to you as well!

**Comment by KafkaNoNeko** [comment]
I've added some ideas for the dataset section (I dug throw the discussion section on kaggle).  Can anyone help me rephrase it/clean it up?  Thanks!
